// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SegurosFYP.Entities.xd
{
    public partial class tbCategoriasPorTipoPlan
    {
        public tbCategoriasPorTipoPlan()
        {
            tbFacturaMedicaDetalle = new HashSet<tbFacturaMedicaDetalle>();
        }

        public int Categ_Id { get; set; }
        public string Categ_Descripcion { get; set; }
        public int Categ_UsuarioCreacion { get; set; }
        public DateTime Categ_FechaCreacion { get; set; }
        public int? Categ_UsuarioModificacion { get; set; }
        public DateTime? Categ_FechaModificacion { get; set; }
        public bool? Categ_Estado { get; set; }

        public virtual ICollection<tbFacturaMedicaDetalle> tbFacturaMedicaDetalle { get; set; }
    }
}