// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SegurosFYP.Entities.Entities
{
    public partial class tbCoberturas
    {
        public tbCoberturas()
        {
            tbTiposPlanes = new HashSet<tbTiposPlanes>();
        }

        public int Cober_Id { get; set; }
        public string Cober_Descripcion { get; set; }
        public int Cober_UsuarioCreacion { get; set; }
        public DateTime Cober_FechaCreacion { get; set; }
        public int? Cober_UsuarioModificacion { get; set; }
        public DateTime? Cober_FechaModificacion { get; set; }
        public bool? Cober_Estado { get; set; }

        public virtual tbUsuarios Cober_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Cober_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbTiposPlanes> tbTiposPlanes { get; set; }
    }
}