// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SegurosFYP.Entities.Entities
{
    public partial class tbDesembolsos
    {
        public tbDesembolsos()
        {
            tbFacturaMedicaEncabezado = new HashSet<tbFacturaMedicaEncabezado>();
            tbPrescripciones = new HashSet<tbPrescripciones>();
        }

        public int Desem_Id { get; set; }
        public int Clien_Id { get; set; }
        public int Infor_Id { get; set; }
        public int Desem_UsuarioCreacion { get; set; }
        public DateTime Desem_FechaCreacion { get; set; }
        public int? Desem_UsuarioModificacion { get; set; }
        public DateTime? Desem_FechaModificacion { get; set; }
        public bool? Desem_Estado { get; set; }

        public virtual tbPersonas Clien { get; set; }
        public virtual tbUsuarios Desem_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Desem_UsuarioModificacionNavigation { get; set; }
        public virtual tbInformeMedico Infor { get; set; }
        public virtual ICollection<tbFacturaMedicaEncabezado> tbFacturaMedicaEncabezado { get; set; }
        public virtual ICollection<tbPrescripciones> tbPrescripciones { get; set; }
    }
}