// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SegurosFYP.Entities.Entities
{
    public partial class tbEnfermedades
    {
        public int Enfer_Id { get; set; }
        public string Enfer_Descripcion { get; set; }
        public int Enfer_UsuarioCreacion { get; set; }
        public DateTime Enfer_FechaCreacion { get; set; }
        public int? Enfer_UsuarioModificacion { get; set; }
        public DateTime? Enfer_FechaModificacion { get; set; }
        public bool? Enfer_Estado { get; set; }

        public virtual tbUsuarios Enfer_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Enfer_UsuarioModificacionNavigation { get; set; }
        [NotMapped]
        public string UsuarioCreacion { get; set; }
        [NotMapped]
        public string UsuarioModificacion { get; set; }
    }
}