// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SegurosFYP.Entities.Entities
{
    public partial class tbFrecuencias
    {
        public tbFrecuencias()
        {
            tbInformacionMedicaInmed_DrogasEstimulantesFrecuenciaNavigation = new HashSet<tbInformacionMedica>();
            tbInformacionMedicaInmed_FumarFrecuenciaNavigation = new HashSet<tbInformacionMedica>();
            tbInformacionMedicaInmed_IngiereFrecuenciaNavigation = new HashSet<tbInformacionMedica>();
        }

        public int Frecu_Id { get; set; }
        public string Frecu_Descripcion { get; set; }
        public int Frecu_UsuarioCreacion { get; set; }
        public DateTime Frecu_FechaCreacion { get; set; }
        public int? Frecu_UsuarioModificacion { get; set; }
        public DateTime? Frecu_FechaModificacion { get; set; }
        public bool? Frecu_Estado { get; set; }

        public virtual tbUsuarios Frecu_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Frecu_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbInformacionMedica> tbInformacionMedicaInmed_DrogasEstimulantesFrecuenciaNavigation { get; set; }
        public virtual ICollection<tbInformacionMedica> tbInformacionMedicaInmed_FumarFrecuenciaNavigation { get; set; }
        public virtual ICollection<tbInformacionMedica> tbInformacionMedicaInmed_IngiereFrecuenciaNavigation { get; set; }

        [NotMapped]
        public string UsuarioCreacion { get; set; }
        [NotMapped]
        public string UsuarioModificacion { get; set; }
    }
}