// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SegurosFYP.Entities.Entities
{
    public partial class tbIdentificaciones
    {
        public tbIdentificaciones()
        {
            tbPersonas = new HashSet<tbPersonas>();
        }

        public int Ident_Id { get; set; }
        public int Tiden_Id { get; set; }
        public string Ident_NumeroIdentificacion { get; set; }
        public DateTime Ident_FechaNacimiento { get; set; }
        public string Ident_LugarNacimiento { get; set; }
        public int Ident_UsuarioCreacion { get; set; }
        public DateTime Ident_FechaCreacion { get; set; }
        public int? Ident_UsuarioModificacion { get; set; }
        public DateTime? Ident_FechaModificacion { get; set; }
        public bool? Ident_Estado { get; set; }


        [NotMapped]
        public string usua_creac { get; set; }

        [NotMapped]
        public string usua_modi { get; set; }
        public virtual tbUsuarios Ident_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Ident_UsuarioModificacionNavigation { get; set; }
        public virtual tbTiposIdentificaciones Tiden { get; set; }
        public virtual ICollection<tbPersonas> tbPersonas { get; set; }
    }
}