// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SegurosFYP.Entities.Entities
{
    public partial class tbInformeMedico
    {
        public tbInformeMedico()
        {
            tbReclamos = new HashSet<tbReclamos>();
        }

        public int Infor_Id { get; set; }
        public string Infor_Diagnostico { get; set; }
        public string Infor_TratamientoRealizado { get; set; }
        public string Infor_TratamientoProgramado { get; set; }
        public string Infor_OtrosTratamientos { get; set; }
        public string Infor_DocumentoAdelante { get; set; }
        public string Infor_DocumentoAtras { get; set; }
        public int Infor_UsuarioCreacion { get; set; }
        public DateTime Infor_FechaCreacion { get; set; }
        public int? Infor_UsuarioModificacion { get; set; }
        public DateTime? Infor_FechaModificacion { get; set; }
        public bool? Infor_Estado { get; set; }

        public virtual ICollection<tbReclamos> tbReclamos { get; set; }
    }
}