// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SegurosFYP.Entities.Entities
{
    public partial class tbMunicipios
    {
        public tbMunicipios()
        {
            tbPersonas = new HashSet<tbPersonas>();
        }

        public string Munic_Id { get; set; }
        public string Munic_Descripcion { get; set; }
        [NotMapped]
        public string Depar_Descripcion { get; set; }

        public string Depar_Id { get; set; }
        public int Munic_UsuarioCreacion { get; set; }
        public DateTime Munic_FechaCreacion { get; set; }
        public int? Munic_UsuarioModificacion { get; set; }
        public DateTime? Munic_FechaModificacion { get; set; }
        public bool? Munic_Estado { get; set; }

        public virtual tbDepartamentos Depar { get; set; }
        public virtual tbUsuarios Munic_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Munic_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbPersonas> tbPersonas { get; set; }

        [NotMapped]
        public string UsuarioCreacion { get; set; }
        [NotMapped]
        public string UsuarioModificacion { get; set; }
    }

}