// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SegurosFYP.Entities.Entities
{
    public partial class tbParentescos
    {
        public tbParentescos()
        {
            tbPersonas = new HashSet<tbPersonas>();
        }

        public int Paren_Id { get; set; }
        public string Paren_Descripcion { get; set; }
        public int Paren_UsuarioCreacion { get; set; }
        public DateTime Paren_FechaCreacion { get; set; }
        public int? Paren_UsuarioModificacion { get; set; }
        public DateTime? Paren_FechaModificacion { get; set; }
        public bool? Paren_Estado { get; set; }

        public virtual tbUsuarios Paren_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Paren_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbPersonas> tbPersonas { get; set; }
    }
}