// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SegurosFYP.Entities.Entities
{
    public partial class tbPaises
    {
        public tbPaises()
        {
            tbPersonas = new HashSet<tbPersonas>();
        }

        public int Paise_Id { get; set; }
        public string Paise_Descripcion { get; set; }
        public string Paise_Nacionalidad { get; set; }
        public int Paise_UsuarioCreacion { get; set; }
        public DateTime Paise_FechaCreacion { get; set; }
        public int? Paise_UsuarioModificacion { get; set; }
        public DateTime? Paise_FechaModificacion { get; set; }
        public bool? Paise_Estado { get; set; }

        [NotMapped]
        public string UsuarioCreacion { get; set; }
        [NotMapped]
        public string UsuarioModificacion { get; set; }

        public virtual tbUsuarios Paise_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Paise_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbPersonas> tbPersonas { get; set; }
    }
}