// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SegurosFYP.Entities.Entities
{
    public partial class tbPersonas
    {
        public tbPersonas()
        {
            tbDesembolsos = new HashSet<tbDesembolsos>();
            tbFacturaMedicaEncabezado = new HashSet<tbFacturaMedicaEncabezado>();
        }

        public int Perso_Id { get; set; }
        public string Perso_PrimerNombre { get; set; }
        public string Perso_SegundoNombre { get; set; }
        public string Perso_PrimerApellido { get; set; }
        public string Perso_SegundoApellido { get; set; }
        public string Perso_Sexo { get; set; }
        public int Ident_Id { get; set; }
        public int? Estci_Id { get; set; }
        public string Perso_Telefono { get; set; }
        public string Perso_CorreoElectronico { get; set; }
        public string Perso_Direccion { get; set; }
        public string Munic_Id { get; set; }
        public int? Paise_Id { get; set; }
        public int Poliz_Id { get; set; }
        public int Paren_Id { get; set; }
        public int Perso_UsuarioCreacion { get; set; }
        public DateTime Perso_FechaCreacion { get; set; }
        public int? Perso_UsuarioModificacion { get; set; }
        public DateTime? Perso_FechaModificacion { get; set; }
        public bool? Perso_Estado { get; set; }


        public string DniFrenteUrl { get; set; }
        public string DniAtrasUrl { get; set; }

        public virtual tbEstadosCiviles Estci { get; set; }
        public virtual tbIdentificaciones Ident { get; set; }
        public virtual tbMunicipios Munic { get; set; }
        public virtual tbPaises Paise { get; set; }
        public virtual tbParentescos Paren { get; set; }
        public virtual tbUsuarios Perso_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Perso_UsuarioModificacionNavigation { get; set; }
        public virtual tbEmpleados tbEmpleados { get; set; }
        public virtual tbInformacionMedica tbInformacionMedica { get; set; }
        public virtual tbPolizas tbPolizas { get; set; }
        public virtual ICollection<tbDesembolsos> tbDesembolsos { get; set; }
        public virtual ICollection<tbFacturaMedicaEncabezado> tbFacturaMedicaEncabezado { get; set; }
    }
}