// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SegurosFYP.Entities.Entities
{
    public partial class tbPolizas
    {
        public int Poliz_Id { get; set; }
        public int Clien_Id { get; set; }
        public int Tipos_Id { get; set; }
        public int Emple_Id { get; set; }
        public int Poliz_Cuotas { get; set; }
        public bool Poliz_TipoPago { get; set; }
        public bool Poliz_EstadoCuotasPoliza { get; set; }
        public int Poliz_UsuarioCreacion { get; set; }
        public DateTime Poliz_FechaCreacion { get; set; }
        public int? Poliz_UsuarioModificacion { get; set; }
        public DateTime? Poliz_FechaModificacion { get; set; }
        public bool? Poliz_Estado { get; set; }

   
        public string Emple_NombreCompleto { get; set; }
  
        public string Clien_NombreCompleto { get; set; }

        public string Tipos_Descripcion { get; set; }

        public virtual tbPersonas Clien { get; set; }
        public virtual tbEmpleados Emple { get; set; }
        public virtual tbUsuarios Poliz_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Poliz_UsuarioModificacionNavigation { get; set; }
        public virtual tbTiposPlanes Tipos { get; set; }
    }
}