// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SegurosFYP.Entities.Entities
{
    public partial class tbQuejas
    {
        public int Queja_Id { get; set; }
        public int Clien_Id { get; set; }
        public string Queja_Descripcion { get; set; }
        public int Queja_UsuarioCreacion { get; set; }
        public DateTime Queja_FechaCreacion { get; set; }
        public int? Queja_UsuarioModificacion { get; set; }
        public DateTime? Queja_FechaModificacion { get; set; }
        public bool? Queja_Estado { get; set; }

        public virtual tbUsuarios Queja_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Queja_UsuarioModificacionNavigation { get; set; }
    }
}