// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SegurosFYP.Entities.Entities
{
    public partial class tbTiposIdentificaciones
    {
        public tbTiposIdentificaciones()
        {
            tbIdentificaciones = new HashSet<tbIdentificaciones>();
        }

        public int Tiden_Id { get; set; }
        public string Tiden_Descripcion { get; set; }
        public int Tiden_UsuarioCreacion { get; set; }
        public DateTime Tiden_FechaCreacion { get; set; }
        public int? Tiden_UsuarioModificacion { get; set; }
        public DateTime? Tiden_FechaModificacion { get; set; }
        public bool? Tiden_Estado { get; set; }

        public virtual tbUsuarios Tiden_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Tiden_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbIdentificaciones> tbIdentificaciones { get; set; }
    }
}