// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SegurosFYP.Entities.Entities
{
    public partial class tbTipoArticuloMedico
    {
        public tbTipoArticuloMedico()
        {
            tbInformacionMedicaInmed_TipoAlcoholNavigation = new HashSet<tbInformacionMedica>();
            tbInformacionMedicaInmed_TipoDrogasEstimulantesNavigation = new HashSet<tbInformacionMedica>();
            tbInformacionMedicaInmed_TipoFumarNavigation = new HashSet<tbInformacionMedica>();
        }

        public int Tarme_Id { get; set; }
        public int Tarme_Tipo { get; set; }
        public string Tarme_Descripcion { get; set; }
        public int Tarme_UsuarioCreacion { get; set; }
        public DateTime Tarme_FechaCreacion { get; set; }
        public int? Tarme_UsuarioModificacion { get; set; }
        public DateTime? Tarme_FechaModificacion { get; set; }
        public bool? Tarme_Estado { get; set; }

        public virtual tbUsuarios Tarme_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Tarme_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbInformacionMedica> tbInformacionMedicaInmed_TipoAlcoholNavigation { get; set; }
        public virtual ICollection<tbInformacionMedica> tbInformacionMedicaInmed_TipoDrogasEstimulantesNavigation { get; set; }
        public virtual ICollection<tbInformacionMedica> tbInformacionMedicaInmed_TipoFumarNavigation { get; set; }
    }
}