// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SegurosFYP.Entities.Entities
{
    public partial class tbUsuarios
    {
        public tbUsuarios()
        {
            tbPantallasPanta_UsuarioCreacionNavigation = new HashSet<tbPantallas>();
            tbPantallasPanta_UsuarioModificacionNavigation = new HashSet<tbPantallas>();
            tbPantallasPorRolesPapro_UsuarioCreacionNavigation = new HashSet<tbPantallasPorRoles>();
            tbPantallasPorRolesPapro_UsuarioModificacionNavigation = new HashSet<tbPantallasPorRoles>();
            tbRolesRoles_UsuarioCreacionNavigation = new HashSet<tbRoles>();
            tbRolesRoles_UsuarioModificacionNavigation = new HashSet<tbRoles>();
        }

        public int Usuar_Id { get; set; }
        public string Usuar_Usuario { get; set; }
        public string Usuar_Contrasena { get; set; }
        public int Emple_Id { get; set; }
        public int Roles_Id { get; set; }
        public bool Usuar_Admin { get; set; }
        public DateTime Usuar_UltimaSesion { get; set; }
        public int Usuar_UsuarioCreacion { get; set; }
        public DateTime Usuar_FechaCreacion { get; set; }
        public int? Usuar_UsuarioModificacion { get; set; }
        public DateTime? Usuar_FechaModificacion { get; set; }
        public bool? Usuar_Estado { get; set; }

        public virtual ICollection<tbPantallas> tbPantallasPanta_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbPantallas> tbPantallasPanta_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbPantallasPorRoles> tbPantallasPorRolesPapro_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbPantallasPorRoles> tbPantallasPorRolesPapro_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRolesRoles_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRolesRoles_UsuarioModificacionNavigation { get; set; }
    }
}