// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SegurosFYP.Entities.kkkk
{
    public partial class tbDesembolsos
    {
        public int Desem_Id { get; set; }
        public int Recla_Id { get; set; }
        public decimal? Desem_TotalAcreditar { get; set; }
        public int Desem_UsuarioCreacion { get; set; }
        public DateTime Desem_FechaCreacion { get; set; }
        public int? Desem_UsuarioModificacion { get; set; }
        public DateTime? Desem_FechaModificacion { get; set; }
        public bool? Desem_Estado { get; set; }

        public virtual tbReclamos Recla { get; set; }
    }
}