// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SegurosFYP.Entities.kkkk
{
    public partial class tbFacturaMedicaEncabezado
    {
        public tbFacturaMedicaEncabezado()
        {
            tbFacturaMedicaDetalle = new HashSet<tbFacturaMedicaDetalle>();
        }

        public int Faenca_Id { get; set; }
        public string Faenca_Codigo { get; set; }
        public int Clien_Id { get; set; }
        public string Faenca_HospitalClinica { get; set; }
        public DateTime Faenca_FechaImpresion { get; set; }
        public int Recla_Id { get; set; }
        public string Factu_DocumentoAdelante { get; set; }
        public string Factu_DocumentoAtras { get; set; }
        public int Faenca_UsuarioCreacion { get; set; }
        public DateTime Faenca_FechaCreacion { get; set; }
        public int? Faenca_UsuarioModificacion { get; set; }
        public DateTime? Faenca_FechaModificacion { get; set; }
        public bool? Faenca_Estado { get; set; }

        public virtual tbReclamos Recla { get; set; }
        public virtual ICollection<tbFacturaMedicaDetalle> tbFacturaMedicaDetalle { get; set; }
    }
}